package euler.test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

// 問題4：斜め読み
// 以下のような 484 文字の文字列がある。
//
// VACLHTNAXQFTROTDPASCKNZSLRKSACOSBDXIDCGFOOFLNQVHVI
// YMHINMTQDNZAQBYCRRDSTPGCIOFBAHICHNTFNLRFCTEBIDBGOB
// QCTPVYOOKXKCKLBSLSIBTKVGKEPZTMDGRKDSCATYHFMSAVVYEN
// GITTSOHGLNCMGHZDDGEKPYYVYYMHKESHASASRFMKOSNVLQIBVT
// NNONFGXGBDLOFLAKZLGRPMOLXVMFIYIKQZBGVKTBYGTAPCHXOK
// MHRSHCGIVYEDPHLCIMPXPRCPRATHHHDPZVMLQEXQPQDPLCZKOE
// CKOGHCSLSIISMXGNZFCMVGRACCCRKLDOTXRLHSVTGOZYPOAIXO
// XMGAFDOMCXYXALTFETPVLMBNZHEMEVZDMVESCMBFLTZARKZFAZ
// OHLTKXLNHZZGVFIGLOGDNFDSNBQGIAKNXSXNZMFHNFTCMPDIPS
// RFPPFQHISEVIHNMTIPCGHLSIKHSTZKGLZS
//
// この文字列を 1 行 22 文字の形(全部で 22 行)に書き直したとする。
// ※最初の 3 行のみを示す。
//
// VACLHTNAXQFTROTDPASCKN
// ZSLRKSACOSBDXIDCGFOOFL
// NQVHVIYMHINMTQDN....
//
// 左上から右下に至る対角線上にある文字を拾ってできる、22 文字の文字列を答えよ。
public class Test4 {
  public static void main(String[] args) {
    String string = "VACLHTNAXQFTROTDPASCKN" +
                    "ZSLRKSACOSBDXIDCGFOOFLNQVHVI" +
            "YMHINMTQDNZAQBYCRRDSTPGCIOFBAHICHNTFNLRFCTEBIDBGOB" +
            "QCTPVYOOKXKCKLBSLSIBTKVGKEPZTMDGRKDSCATYHFMSAVVYEN" +
            "GITTSOHGLNCMGHZDDGEKPYYVYYMHKESHASASRFMKOSNVLQIBVT" +
            "NNONFGXGBDLOFLAKZLGRPMOLXVMFIYIKQZBGVKTBYGTAPCHXOK" +
            "MHRSHCGIVYEDPHLCIMPXPRCPRATHHHDPZVMLQEXQPQDPLCZKOE" +
            "CKOGHCSLSIISMXGNZFCMVGRACCCRKLDOTXRLHSVTGOZYPOAIXO" +
            "XMGAFDOMCXYXALTFETPVLMBNZHEMEVZDMVESCMBFLTZARKZFAZ" +
            "OHLTKXLNHZZGVFIGLOGDNFDSNBQGIAKNXSXNZMFHNFTCMPDIPS" +
            "RFPPFQHISEVIHNMTIPCGHLSIKHSTZKGLZS";

    List<String> list = new ArrayList<>();

    for (int i = 1; i <=22; i++) {
      list.add(string.substring(i*22-22,i*22));
    }
    System.out.println(list);

    for (int i = 0; i <=21 ; i++) {
      System.out.print(list.get(i).charAt(i));
    }
  }

}


